### ISSUE TITLE
Remove const title and hardcoded loading text

### ISSUE THREAD

**Issue by wal33d006** [KarimMohamed2005/SplashScreenFlutterPackage#14]
The title should be completely exposed to the creator, if someone doesn't want anything under their Logo, it's currently not possible in the package. 
Also, expose the text under the loader to the creator, for suppose, I didn't want any text to appear below my loader so I couldn't do anything about it except for copying your code and modifying it.

**Comment by KarimMohamed2005** [comment]
Resolved.
