### ISSUE TITLE
Convert the Texts "Loading" and "Now" as parameters in the SplashScreen class

### ISSUE THREAD

**Issue by marvlm** [KarimMohamed2005/SplashScreenFlutterPackage#17]
User should be able to customize the words below the CircularProgressIndicator:

Text("**Loading**",style: widget.styleTextUnderTheLoader
 ),
 new Center(child: Text("**Now**",style: widget.styleTextUnderTheLoader
 ),

**Comment by abderman25** [comment]
Totally agree with you on that,

**Comment by MohAbdelhamed** [comment]
Thank you.. Great job. 👍 👍
