### ISSUE TITLE
how to fill splash screen image to screen??

### ISSUE THREAD

**Issue by TusharAswal** [KarimMohamed2005/SplashScreenFlutterPackage#19]
Is there any way to compleately fill hight width with certain image ?? photoSize currently takes an integer and its hard to provide specific data for filling an image to splash screen.

**Comment by samycodes** [comment]
You can use Stack
Put Splashcreen first and then put an image to fill whole screen.

**Comment by ahmedmgh67** [comment]
there is backgroundImage property

**Comment by SonQBChau** [comment]
It would be nice to add an option to control BoxFit in backgroundImage. Stack solution works though.

**Comment by HePeng11** [comment]
hi, how can I use the backgoundImage property?  how create the object value

**Comment by HePeng11** [comment]
ok, TKS,  I could use AssetImage

**Comment by HePeng11** [comment]
hi samycodes, i tried the code,and found that it will show a white splash screen before rendering container
