### ISSUE TITLE
After add the splash screen, there is a back button at AfterSplash page

### ISSUE THREAD

**Issue by jiachangyang1025** [KarimMohamed2005/SplashScreenFlutterPackage#2]
After adding a splash screen, a back button showed at AfterSplash page, and you can press back button and back to splash screen. How can i disable the back button?

**Comment by KarimMohamed2005** [comment]
I can't explain this thing but i will edit navigation in package and after
i edit it search about how to disable it

**Comment by fvdeveloper** [comment]
@jiachangyang1025 This should fix it. 

appBar: AppBar(
        automaticallyImplyLeading: false,
          title: Text("Welcome In SplashScreen Package")
      ),

**Comment by KarimMohamed2005** [comment]
_**@fvdeveloper**_
 thanks For Your Answer It 's True .
