### ISSUE TITLE
How to kill splash screen after navigation new screen

### ISSUE THREAD

**Issue by eddydn** [KarimMohamed2005/SplashScreenFlutterPackage#5]
How to kill splash screen after navigation new screen

**Comment by eddydn** [comment]
Like you navigation new screen after show splash screen , i want to press back button it will not show splash screen :D 

Like Finish(); method in Android calling on SplashSCreen after start new activity

**Comment by AndrewLowther** [comment]
You can override both the dispose and deactivate methods for example to replace the splash screen with an empty container.

```dart
@override
void deactivate() {
  super.deactivate();
  // Replace your splash screen with an empty container
  _SplashScreen.child = new Container();
}
```
