### ISSUE TITLE
 Can't return a value from a void function

### ISSUE THREAD

**Issue by NTMS2017** [KarimMohamed2005/SplashScreenFlutterPackage#9]
I am having an issue as shown below.

```
compiler message: file:///Users/niyazitoros/.pub-cache/hosted/pub.dartlang.org/splashscreen-1.1.0/lib/splashscreen.dart:49:40: Warning: Can't return a value from a void function.
compiler message:           return **Navigator.of(context).pushReplacementNamed(widget.navigateAfterSeconds);**
compiler message:                                        ^
compiler message: file:///Users/niyazitoros/.pub-cache/hosted/pub.dartlang.org/splashscreen-1.1.0/lib/splashscreen.dart:51:40: Warning: Can't return a value from a void function.
compiler message:           r### eturn Navigator.of(context).pushReplacement(new MaterialPageRoute(builder: (BuildContext context) => widget.navigateAfterSeconds));
compiler message:  
```

Niyazis-MBP:capital_splash niyazitoros$ **dart --version**
Dart VM version: 2.0.0-dev.69.5 (Tue Jul 31 15:05:14 2018 +0200) on "macos_x64"

Niyazis-MBP:capital_splash niyazitoros$ **flutter --version**
Flutter 0.8.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5ab9e70727 (3 weeks ago) • 2018-09-07 12:33:05 -0700
Engine • revision 58a1894a1c

**Comment by ram231** [comment]
Does this cause error to your app?

**Comment by NTMS2017** [comment]
No, it doesnt cause any errro yet but it looks little bit anoying to see everytime in console, when I am trying to test my app. Thanks for great plugin anyway.

**Comment by ram231** [comment]
the fat arrow is just a syntactic sugar for one-line return statement. if you do the `builder: (BuildContext context) { widget.navigateAfterSeconds();` then that wouldn't return anything at all.
